"""...

Revision ID: 52ed9a70ba11
Revises: 
Create Date: 2025-06-28 11:15:28.703759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ed9a70ba11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('transazione_ricorrente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.String(length=100), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=7), nullable=False),
    sa.Column('data_inizio', sa.Date(), nullable=False),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.Column('frequenza', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.String(length=100), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=7), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('prevista', sa.Boolean(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transazione')
    op.drop_table('transazione_ricorrente')
    op.drop_table('categoria')
    # ### end Alembic commands ###
