"""Aggiunto budget predefinito a Categoria

Revision ID: 5f29a0d2e38d
Revises: b4d881b6a4c8
Create Date: 2025-06-29 18:52:41.008918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f29a0d2e38d'
down_revision = 'b4d881b6a4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_predefinito', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_column('budget_predefinito')

    # ### end Alembic commands ###
