"""Aggiunta tabella Budget

Revision ID: 876d28b00403
Revises: 52ed9a70ba11
Create Date: 2025-06-28 16:47:00.869320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876d28b00403'
down_revision = '52ed9a70ba11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importo_limite', sa.Float(), nullable=False),
    sa.Column('mese', sa.Integer(), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_id', 'mese', 'anno', name='_cat_mese_anno_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget')
    # ### end Alembic commands ###
