"""Rimosso campo 'prevista' da Transazione

Revision ID: b4d881b6a4c8
Revises: 876d28b00403
Create Date: 2025-06-29 16:09:26.369216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d881b6a4c8'
down_revision = '876d28b00403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transazione', schema=None) as batch_op:
        batch_op.drop_column('prevista')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transazione', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prevista', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
